### ISSUE TITLE
UAT | Order | Type of hearings

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1565]
To the list of Purpose of Hearings:
1. Remove Admin
2. Add Appearance, Examination of Accused

**Comment by rkanala517** [comment]
This change request has been fixed. Please check the reference here,
1. Admin option had been removed from the dropdown_  https://jam.dev/c/1254287b-7b05-4442-bf05-d4e8ebe76888
2.Appearance, Examination of Accused options have been added to the dropdown_ https://jam.dev/c/1254287b-7b05-4442-bf05-d4e8ebe76888

**Comment by rsi-MaheshVishwanath** [comment]
hi @vaibhavct, The issue persists: In the list of "Purpose of Hearings," the fields are not consistently updated across all areas when scheduling a hearing. Specifically, "Admin" needs to be removed, and "Appearance" and "Examination of Accused" should be added.
step to reproduce: login to judge>> Click on case >>click on action button>> Click on the scheduling of hearing option. Check the purpose of hearing dropdowns.
reproduce step link: https://jam.dev/c/35f7d45b-d64c-42fc-bf2b-0b38ccd19d46

**Comment by Ramu-kandimalla** [comment]
Hi @vaibhavct  @ashishbeehyv  please look into the issue

**Comment by ashishbeehyv** [comment]
hi @rajeshcherukumalli can you please get it re-tested and verified. it is working as expected now.

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
Descriptions: The scheduling order for hearings includes a dropdown menu for selecting the purpose of the hearing. We are removing the "Admin" option from this dropdown and adding two new options: "Appearance" and "Examination of the Accused. This was verified in the solution UAT environment.
 
Employee url: https://dristi-kerala-dev.pucar.org/digit-ui/employee/user/language-selection
 
Test Cases:
1)Verify the "Admin" option remove from the purpose of hearing drop downs with newly registered cases.
2)Verify the "Admin" option remove form the purpose of hearing drop downs with old cases.
3)Verify the ""Appearance" and "Examination of the Accused" option added in the purpose of hearing drop downs with newly registered cases.
4)Verify the ""Appearance" and "Examination of the Accused" option added in the purpose of hearing drop downs with old, registered cases.
5)Verify through **Take action**>>**click generate order tab** >> **selecting the schedule of hearing**>> check the removing the "Admin" option from this dropdown and adding two new options: "Appearance" and "Examination of the Accused" in purpose of hearing 
6)Verify through **Take action**>> **selecting the schedule of hearing**>> check the removing the "Admin" option from this dropdown and adding two new options: "Appearance" and "Examination of the Accused" in purpose of hearing
7)Verify new case through **Admit Case**>>**selecting the schedule of hearing**>> **select date**>>check the removing the "Admin" option from this dropdown and adding two new options: "Appearance" and "Examination of the Accused" in purpose of hearing
8)Verify the newly admitted case by the judge, then click on the case to view the overview page. On the overview page, check the "Schedule Hearing" button. Click on "Schedule Hearing" and ensure that the "Admin" option is removed from the dropdown and verify that two new options, "Appearance" and "Examination of the Accused," have been added under the "Purpose of Hearing."

Reference links:
https://jam.dev/c/204c53e5-e5f5-4de9-afda-796e11f7238c
https://jam.dev/c/d218a439-52df-4078-803e-f03891c7633f

User Ids link: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5-o/edit?gid=0#gid=0
