### ISSUE TITLE
[BUG]: [QA | Bulk Rescheduling | All the hearings which are scheduled are taking up the evening slots.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#3375]
**Describe the bug**
All the hearings which are scheduled are taking up the evening slots.

**Expected behavior**
All the hearings which are scheduled, should take the morning slot and then evening.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b6303279-132d-43c8-8903-b534eda404d8)

**Comment by prasanna2400** [comment]
resolved , now it will take morning slot first then evening

**Comment by iknoorkaur** [comment]
Hi @prasanna2400 , tested in UAT env, not fixed, it is taking up the evening slots first.
Attaching jam video's for ref: https://jam.dev/c/393cd46f-6b61-44a4-951a-195124b28baf
https://jam.dev/c/a388945d-8dee-47f7-8697-6f8607f09d2d

**Comment by prasanna2400** [comment]
updated in uat please retest

**Comment by iknoorkaur** [comment]
Tested in UAT env, working as expected.
Attaching jam video for ref: https://jam.dev/c/37a03f78-9d6d-4804-8907-63fede0d1d22
