### ISSUE TITLE
UAT | E-filing | Review Case Details

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#531]
Module: E-filing
Page: Review Case Details

1) If Complainant/Respondent is from an Entity, Entity Details should be displayed. 
The following should be seperate rows: 1) Company Name 2) Company address
2) View on maps is not redirecting to maps correctly
3) For an available address, the address is shown as undefined multiple times (View image of input address and address on review page)
4) Certain fields blank in cheque details that are mandatory fields (see image)
5) Certain fields where details are not available should show Not Applicable and not blanl
6) For places where documents are attached instead of text added i.e Memorandum of Complaint, Prayer, the field should show 'Document Attached'
7) Advocate Details as a section should show the field and value . in case of party in person, the section for advocate is coming blank

![Image](https://github.com/pucardotorg/dristi/assets/132061840/14d37f82-263a-4ff3-b144-dbe9d3c6a95d)
![Image](https://github.com/pucardotorg/dristi/assets/132061840/bc4e8085-406d-4e28-93e7-b8a38ee9ad57)
![Image](https://github.com/pucardotorg/dristi/assets/132061840/44f5265a-4b50-4c53-bdc4-332aaeb195e6)
![Image](https://github.com/pucardotorg/dristi/assets/132061840/ec9849b4-9075-4525-b7e0-b984c041e1db)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env

**Comment by Taherabharmal** [comment]
1) View on Map is still not working
![Image](https://github.com/user-attachments/assets/b33e2f21-1cd2-4990-87d5-df57090d400b)
![Image](https://github.com/user-attachments/assets/b48e1cb7-652b-4838-8e61-01c5bf12310f)
2) Point 6 i.e For places where documents are attached instead of text added i.e Memorandum of Complaint, Prayer, the field should show 'Document Attached' not working
